#pragma once

#include "Common/BaseDefines.h"

#define FLYENGINE_PLATFORM_BEGIN_NAMESPACE FLYENGINE_BEGIN_NAMESPACE(platform)
#define USING_FLYENGINE_PLATFORM_NAMESPACE USING_FLYENGINE_NAMESPACE(platform)