#pragma once

#define FLYENGINE_BEGIN_NAMESPACE(Name) \
    namespace Name                      \
    {
#define FLYENGINE_END_NAMESPACE }

#define USING_FLYENGINE_NAMESPACE(Name) using namespace Name;

#define FLYENGINE_CORE_BEGIN_NAMESPACE FLYENGINE_BEGIN_NAMESPACE(Core)
#define USING_FLYENGINE_CORE_NAMESPACE USING_FLYENGINE_NAMESPACE(Core)